version: '2'
services:
    tictactoe-app:
        image: tictactoe
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tictactoe-mysql:3306/tictactoe?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tictactoe-mysql:
        extends:
            file: mysql.yml
            service: tictactoe-mysql
